export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import './globals.css';
import Header from "@/app/_components/header/Header";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
      <html lang="en">
      <body>
      {/* Header Layout */}
      <Header/>
      {/* Page Content */}
      <main>{children}</main>
      </body>
      </html>
  )
}
