spring.application.name=board

#dbms
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.username=root
#spring.datasource.password=1234

spring.datasource.url=jdbc:h2:tcp://localhost/~/test
spring.datasource.username=sa
spring.datasource.password=
spring.data.jdbc.dialect=oracle

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.hibernate.ddl-auto=create

#log
logging.level.org.springframework.web=DEBUG


#JPA log
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG
logging.level.org.hibernate.resource.transaction=DEBUG

logging.level.org.hibernate.sql=DEBUG

#Swagger
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json
springdoc.api-docs.groups.enabled=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha

# swagger-ui custom path
#springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.paths-to-match=/**

# JWT Configuration
#jwt.access-secret=secretkeysecretkeysecretkeysecretkeysecretkeysecretkey
#jwt.refresh-secret=secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey
#jwt.access-expiration=600000 # 10 min: 10min * 60 sec * 1000 millisecond
#jwt.refresh-expiration=10800000 # 3 hours: 3hours * 60min * 60sec * 1000 millisecond
app.auth.refreshTokenExpirationMs=10800000
app.auth.tokenSecret=f8cf543a633d2a4f1b89b7f6976208cb252558ed98f378d545052bd3e61f229b4c501fe4dc77a6466dcb1091f442200af96a471822e2a6fe542d553549bee036
app.auth.tokenExpirationMs=6000000
#app.auth.tokenExpirationMs=1000
spring.jwt.secret=f8cf543a633d2a4f1b89b7f6976208cb252558ed98f378d545052bd3e61f229b4c501fe4dc77a6466dcb1091f442200af96a471822e2a6fe542d553549bee036
spring.security.user.name = test1
spring.security.user.password = 123123

# jasypt
jasypt.encryptor.bean=jasyptStringEncryptor
#jasypt.encryptor.password=passpasspass

#slack
slack.webhook.url=ENC(EcFg/6qTQ3sxEXVUYK/y79w8jMPPQqfX5KNkJAYfjf+Sgd3bj+6hKingZijZWKKMJv7fHMkWPSLPBQ3tYj+86YfjqevUmLgfjPP+rvkWFCMC7lLadIDI1xcjyQCsareh)

#redis
server.servlet.session.cookie.name=JSESSIONID
spring.session.redis.namespace=board:session
spring.data.redis.host=localhost
spring.data.redis.password=1234
spring.data.redis.port=6379